spring.application.name=saasurlshortner

# application.properties
spring.datasource.url=jdbc:postgresql://localhost:5433/urlshortner
spring.datasource.username=imprint
spring.datasource.password=testyAdmin
spring.datasource.driver-class-name=org.postgresql.Driver
saasurl.jwt.secret=yGN0UUQnYgFICDtmUfEKgCp03vxf6ZPqU7ZEjNgdjxL

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
